#!/bin/zsh
activeborder=#b24a3c
inactiveborder=#b2adab

text1=#c0594b
text2=#fcf467
text3=#fff0ea
text4=#c0594b
text5=#ddd9d7
text1d=#c0594b
text2d=#fcf467
text3d=#fff0ea
text4d=#b9b5b2
text5d=#ddd9d7
focus1=#fcf467
focus1d=#746658
active=#fcf467
inactive=#746658
warn=#fcf467
bg1=#42433f
bg2=#b9b5b2

