#!/bin/zsh
activeborder=#00E8CF
inactiveborder=#117B82
#[colors]
#;green
text1=#17EBA0
#;teal
text2=#82FFF2
#;purple
text3=#7630EA
#;yellow
text4=#FEC901
#;red
text5=#C54E4B
#;orange
text6=#FF8300
#;blue
text7=#00739D

text1d=#008567
text2d=#117B82
text3d=#6633BC
text4d=#9B6310
text5d=#A2423D
text6d=#8D741C
text7d=#00567A

#;teal
focus1=#00E8CF
focus1d=#117B82

#;teal
active=#00E8CF
inactive=#117B82

#;orange
warn=#C54E4B

#;grey
bg1=#263040

#;light grey
bg2=#404B5C
